const dayjs = require("dayjs");
var utc = require("dayjs/plugin/utc");
dayjs.extend(utc);
var arraySupport = require("dayjs/plugin/arraySupport");
dayjs.extend(arraySupport);
var bigIntSupport = require("dayjs/plugin/bigIntSupport");
dayjs.extend(bigIntSupport);
var calendar = require("dayjs/plugin/calendar");
dayjs.extend(calendar);
var dayOfYear = require("dayjs/plugin/dayOfYear");
dayjs.extend(dayOfYear);
var duration = require("dayjs/plugin/duration");
dayjs.extend(duration);
var isBetween = require("dayjs/plugin/isBetween");
dayjs.extend(isBetween);
var isLeapYear = require("dayjs/plugin/isLeapYear");
dayjs.extend(isLeapYear);
var isSameOrAfter = require("dayjs/plugin/isSameOrAfter");
dayjs.extend(isSameOrAfter);
var isSameOrBefore = require("dayjs/plugin/isSameOrBefore");
dayjs.extend(isSameOrBefore);
var isToday = require("dayjs/plugin/isToday");
dayjs.extend(isToday);
var isTomorrow = require("dayjs/plugin/isTomorrow");
dayjs.extend(isTomorrow);
var isYesterday = require("dayjs/plugin/isYesterday");
dayjs.extend(isYesterday);
var isoWeek = require("dayjs/plugin/isoWeek");
dayjs.extend(isoWeek);
var isoWeeksInYear = require("dayjs/plugin/isoWeeksInYear");
var isLeapYear = require("dayjs/plugin/isLeapYear"); // dependent on isLeapYear plugin
dayjs.extend(isoWeeksInYear);
dayjs.extend(isLeapYear);
var localeData = require("dayjs/plugin/localeData");
dayjs.extend(localeData);
dayjs().localeData();
var localizedFormat = require("dayjs/plugin/localizedFormat");
dayjs.extend(localizedFormat);
var minMax = require("dayjs/plugin/minMax");
dayjs.extend(minMax);
var objectSupport = require("dayjs/plugin/objectSupport");
dayjs.extend(objectSupport);
var pluralGetSet = require("dayjs/plugin/pluralGetSet");
dayjs.extend(pluralGetSet);
var quarterOfYear = require("dayjs/plugin/quarterOfYear");
dayjs.extend(quarterOfYear);
var relativeTime = require("dayjs/plugin/relativeTime");
dayjs.extend(relativeTime);
var toArray = require("dayjs/plugin/toArray");
dayjs.extend(toArray);
var toObject = require("dayjs/plugin/toObject");
dayjs.extend(toObject);
var updateLocale = require("dayjs/plugin/updateLocale");
dayjs.extend(updateLocale);
var utc = require("dayjs/plugin/utc");
dayjs.extend(utc);
var weekOfYear = require("dayjs/plugin/weekOfYear");
dayjs.extend(weekOfYear);
var weekYear = require("dayjs/plugin/weekYear"); // dependent on weekOfYear plugin
var weekOfYear = require("dayjs/plugin/weekOfYear");
dayjs.extend(weekOfYear);
dayjs.extend(weekYear);
var weekday = require("dayjs/plugin/weekday");
dayjs.extend(weekday);
var utc = require("dayjs/plugin/utc");
var timezone = require("dayjs/plugin/timezone"); // dependent on utc plugin
dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.extend(relativeTime);
dayjs.extend(isSameOrAfter);
dayjs.extend(isBetween);
dayjs.extend(isLeapYear);

const now = dayjs();

console.log(now);
