const data = [
  {
    id: 1,
    first_name: "Heloise",
    last_name: "Offin",
    full_name: "Heloise Offin John",
    //word_length : 4 define full_name last word length.
    email: "hoffin0@cbslocal.com",
    // email property's in domain name if not a .com else email name change and name invalid_name.
    gender: "Female",
    ip_address: "11.99.26.126",
    // ip_adderss property in if first number's length are not 3 else remove ip_address property.
  },
  {
    id: 2,
    first_name: "Thurstan",
    last_name: "Matzl",
    full_name: "Thurstan Matzl George",
    email: "tmatzl1@livejournal.com",
    gender: "Male",
    ip_address: "141.136.129.177",
  },
  {
    id: 3,
    first_name: "Brandie",
    last_name: "Cypler",
    full_name: "Brandie Cypler Joe ",
    email: "bcypler2@nbcnews.com",
    gender: "Female",
    ip_address: "71.158.59.89",
  },
  {
    id: 4,
    first_name: "Vasily",
    last_name: "Ahern",
    full_name: "Vasily Ahern Andrew",
    email: "vahern3@ocn.ne.jp",
    gender: "Male",
    ip_address: "1.219.106.195",
  },
  {
    id: 5,
    first_name: "Ashlie",
    last_name: "Prangley",
    full_name: "Ashlie Prangley Matt ",
    email: "aprangley4@google.co.jp",
    gender: "Female",
    ip_address: "212.124.76.72",
  },
  {
    id: 6,
    first_name: "Geordie",
    last_name: "Sawforde",
    full_name: "Geordie Sawforde",
    email: "gsawforde5@dedecms.com",
    gender: "Male",
    ip_address: "189.115.55.16",
  },
  {
    id: 7,
    first_name: "Anestassia",
    last_name: "Elrick",
    full_name: "Anestassia Elrick  Ervine",
    email: "aelrick6@wiley.com",
    gender: "Non-binary",
    ip_address: "124.152.153.241",
  },
  {
    id: 8,
    first_name: "Filip",
    last_name: "MacUchadair",
    full_name: "Filip MacUchadair Roy",
    email: "fmacuchadair7@dell.com",
    gender: "Male",
    ip_address: "28.36.18.234",
  },
  {
    id: 9,
    first_name: "Bette",
    last_name: "Krause",
    full_name: "Bette Krause",
    email: "bkrause8@hibu.com",
    gender: "Female",
    ip_address: "26.255.191.197",
  },
  {
    id: 10,
    first_name: "Khalil",
    last_name: "Martinello",
    full_name: "Khalil Martinello ",
    email: "kmartinello9@addthis.com",
    gender: "Male",
    ip_address: "191.169.187.35",
  },
];
